version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo No build, just modules install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'